### ISSUE TITLE
Cannot add OpticalChannel metadata

### ISSUE THREAD

**Issue by alessandratrapani** [catalystneuro/clandinin-lab-to-nwb#13]
If `OpticalChannel` is defined in the imaging interface (BrezovecFunctionalGreenImagingInterface in this case), as follow:
```python
channel_name = 'Green'
metadata["Ophys"]["OpticalChannel"][0].update(
    name=channel_name,
    emission_lambda=513.0,
    description="Green channel of the microscope, 525/50 nm filter.",
    )
```
When I run the conversion, it raises an error when validating an instance under the ophys schema:
```python
ValidationError: Additional properties are not allowed ('OpticalChannel' was unexpected)
Failed validating 'additionalProperties' in schema['properties']['Ophys']:
```
NB: the way I am defining the `OpticalChannel` is the same as for `Device`, but for the Device it does not rise any error.
My guess is that in the `BaseImagingExtractorInterface`, when Ophys metadata are initiated, only `photon_series_type`, `Device` and `ImagingPlane` are defined.
https://github.com/catalystneuro/neuroconv/blob/567213d4b255a62d6b83e34e7a94929cf16c10b2/src/neuroconv/datainterfaces/ophys/baseimagingextractorinterface.py#L33C1-L42C12

**Comment by h-mayorquin** [comment]
Thanks, this is a part of a bigger issue with neuroconv:
https://github.com/catalystneuro/neuroconv/issues/605

We will solve with the solution available with the current means and improve neuroconv to handle this in a better way for the future.
